<!DOCTYPE html>

<!--suppress HtmlUnknownTarget -->
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
  <title>Electronic Voting System</title>
  <!-- Bootstrap core CSS -->
	<link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="bower_components/bootstrap/dist/css/bootstrap-theme.min.css" rel="stylesheet">
  <link href="css/mycss.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="sweetalert-master/dist/sweetalert.css">
 <link rel="stylesheet" type="text/css" href="font-awesome-4.7.0/css/font-awesome.min.css">

</head>
<body>

	{% block content %}{% endblock %}
	
  <script src="bower_components/jquery/dist/jquery.js"></script>
  <script src="sweetalert-master/dist/sweetalert.min.js"></script>
  <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="js/app.js"></script>	
  <script src="js/webcam.js"></script>
  <script src="js/kairos.js"></script>
  <script src="js/kairos_functions.js"></script>
  <script src="js/blockchain.js"></script>
  <script src="js/main.js"></script>
  
  

</body>

</html>
