{% extends "base.phtml" %}

{% block content %}

  <div class= "col-md-1">
    <!--
    <div class= "sidenav" id= "Menu">
      <a class= "closebtn" onclick="closeMenu()">&times;</a>
      <h3 id= "heading">E.V.S<br>User<br>Menu</h3>
      <div class="btn-group-vertical top-buffer">

        <button id="vote_button" class="btn btn-lg btn-block btn-primary">
          <i class="fa fa-key fa-lg"></i> Vote </button>

      <button id="register_button" class="btn btn-lg btn-block btn-primary">
        <i class="fa fa-user-plus fa-lg"></i> Register </button>

        <button id="content_button" class="btn btn-lg btn-block btn-primary">
          <i class="fa fa-users fa-lg"></i> Content </button>

        <button id="scan_portrait" class="btn btn-lg btn-block btn-primary">
          <i class="fa fa-camera fa-lg"></i> Scan Portriat</button>

        <button id="verify_portrait" class="btn btn-lg btn-block btn-primary">
          <i class="fa fa-check fa-lg"></i> Verify Portriat</button>
        -->
        <!--KAIROS REMOVE HACk will be removed after admin page is created-->
        <!--
        <button id="K_hack" class="btn btn-lg btn-primary">Kairos Remove</button>

      </div>

      <div class="top-buffer">

        <p id="logo_n">This System was<br> brought to you by<br><span id="signature"> Konnect</span>


      </div>

    </div>

    <div class="row">
      <span id="sideMenu">&#9776; Menu</span>
    </div>
  -->
  </div>

  <div class= "col-md-10" id= "main">



    <div class="row scheme top-buffer">

      <div class="jumbotron scheme">
        <div class="container text-center">
          <h1 class="header-1">ELECTRONIC VOTING SYSTEM(E.V.S)</h1>
                  <p><i>Quick and Convenient Voting at Your Fingertips.</i><br>
                 <i>Your Vote is Secured Using Blockchain Technologies.</i><br>
               <i>Please Be Aware of your Surroundings while interacting with E.V.S.</i></p>

            <div class="row">

              <div class="col-md-3 col-md-offset-1">
           			<button id="vote_button" class="btn btn-lg btn-block btn-info">
									<i class="fa fa-key fa-lg"></i> Vote </button>
              </div>
				<!--<button id="K_hack" class="btn btn-lg btn-primary">Kairos Remove</button>-->
							<div class="col-md-3 col-md-offset-1">
                <button id="content_button" class="btn btn-lg btn-block btn-info">
                  <i class="fa fa-users fa-lg"></i> Content </button>
              </div>

							<div class="col-md-3 col-md-offset-1">
                <button id="register_button" class="btn btn-lg btn-block btn-info">
                  <i class="fa fa-user-plus fa-lg"></i> Register </button>
              </div>

            </div>

  			</div>
      </div>

    </div>


  <!--  <div class="col-md-12"> -->

      <div class="row text-center top-buffer scheme" id="Login">

          <form class="form-horizontal" id="Login-Form" onsubmit="return login();" method="POST">
            <fieldset>

              <!-- Form Name -->
              <legend>Login</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="user">Registration Number</label>
                <div class="col-md-6">
                  <input id="user" name="user" type="number" placeholder="Enter ID Here" class="form-control input-md" required="">

                </div>
              </div>

              <!-- Password input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="pass">Password</label>
                <div class="col-md-6">
                  <input id="pass" name="pass" type="password" placeholder="Enter Password Here" class="form-control input-md" required="">

                </div>
              </div>

              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="saveL"></label>
                <div class="col-md-4">
                  <button id="login_button" name="saveL" class="btn btn-info btn-block">Login</button>
                </div>
              </div>

            </fieldset>
          </form>

      </div>

    <!-- </div> -->



    <div class="row text-center top-buffer scheme" id="Registration">

      <form id="register_form" onsubmit="return register();" method="POST" action="index.php/registration">
      <fieldset>

      <!-- Form Name -->
      <legend>Registration</legend>
      <legend>Please Enter Information Exactly as it appears on Your National ID</legend>

      <!-- Text input-->
      <div class="form-group col-md-8 col-md-offset-2">
        <div class="col-md-5">
        <label for="RegistrationNumber">Registration Number</label>
        <input id="RegistrationNumber" name="RegistrationNumber" type="number" placeholder="Enter Registration Number" class="form-control input-md" required="">
        </div>

        <div class="col-md-7">
          <label for="Constituency">Constituency</label>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
          <select id="Constituency" name="Constituency" class="form-control">
          <option value="0">Choose Constituency</option>
        </select>
        </div>
        </div>
      </div>

      <!-- Text input-->
      <div class="form-group col-md-8 col-md-offset-2" >
        <div class="col-md-5">
        <label for="Surname">Surname</label>
        <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <input id="Surname" name="Surname" type="text" placeholder="Enter Last Name Here" class="form-control input-md" required="">
        </div>
        </div>

        <div class="col-md-7">
        <label for="GivenNames">Given Names</label>
        <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <input id="GivenNames" name="GivenNames" type="text" placeholder="Enter Other Names Here" class="form-control input-md" required="">
        </div>
        </div>
      </div>

      <!-- Text input-->
      <div class="form-group col-md-8 col-md-offset-2">
        <div class="col-md-5">
        <label for="CountryOfBirth">Country of Birth</label>
        <input id="CountryOfBirth" name="CountryOfBirth" type="text" placeholder="Enter Country of Birth Here" class="form-control input-md" required="">
        </div>

        <div class="col-md-3" style="padding-right: 1px">
        <label for="DateOfBirth">Date of Birth</label>
        <input id="DateOfBirth" name="DateOfBirth" type="date" placeholder="Date of Birth" class="form-control input-md" required="">
        </div>

        <div class="col-md-3">
          <label class="col-md-10" for="Sex">Sex</label>
          <!-- <div class="col-md-1"> -->
            <label class="radio-inline" for="Sex-0">
              <input type="radio" name="Sex" id="Sex-0" value="Male">
              Male
            </label>
            <label class="radio-inline" for="Sex-1">
              <input type="radio" name="Sex" id="Sex-1" value="Female">
              Female
            </label>
          <!-- </div> -->
        </div>
      </div>

      <!-- Text input-->
      <div class="form-group col-md-8 col-md-offset-2">
          <div class="col-md-2">
          <label for="Height">Height</label>
          <input id="HeightFeet" name="Height" type="number" placeholder="Feet" class="form-control input-md" required="" min="1">
          </div>
          <div class="col-md-2">
          <label for="Height">.</label>
          <input id="HeightInches" name="Height" type="number" placeholder="Inches" class="form-control input-md" min="0" max="12">
          </div>

        <div class="col-md-4"  style="padding-left: 76px; padding-right: 1px">
        <label for="DateIssued">Date Issued</label>
        <input id="DateIssued" name="DateIssued" type="date" placeholder="Date Issued" class="form-control input-md" required="">
        </div>

        <div class="col-md-3" style="padding-right: 1px">
        <label for="ExpireDate">Expiration Date</label>
        <input id="ExpireDate" name="ExpireDate" type="date" placeholder="Expiration Date" class="form-control input-md" required="">
        </div>
      </div>

      <div class="form-group col-md-8 col-md-offset-2">
        <div class="col-md-5">
          <label for="Phone">Phone #</label>
          <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
          <input id="Phone" name="Phone" placeholder="1 (473) 123-4567" class="form-control" type="text" required="">
          </div>
        </div>

        <div class="col-md-6">
          <label for="E-Mail">E-Mail</label>
          <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
          <input id="E-Mail" name="E-Mail" placeholder="example@mail.com" class="form-control"  type="email" required="">
          </div>
        </div>
      </div>

      <!-- Button -->
      <div class="form-group col-md-8" style="padding: 20px">
        <label for="saveR"></label>
        <div class="col-md-8">
        <button id="saveR" name="saveR" class="btn btn-info btn-block col-md-8 col-md-offset-8">Next</button>
        </div>
      </div>

      </fieldset>
      </form>

    </div>

    <div class="row top-buffer scheme" id = "image_capture">
      <div class="container">
      <div class="col-md-11 center-block">

      <div class="row top-buffer">
        <div class="text-center">
          <h2>To Ensure Facial Portrait is Captured Successfully:<br></h2>
          <ul id = "lis">
            <li><i>Ensure that a plain background is used.</i></li>
            <li><i>Facial portrait must be centered.</i></li>
            <li><i>Enviroment should contain adequate lighting.</i></li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class = "col-md-3"></div>

        <div class = "col-md-6">
          <button id="swap_camera" class="btn btn-md btn-info"><i class="fa fa-camera-retro fa-lg"></i> <strong> Retake Portrait</strong></button>
          <button id="save_snapshot" class="btn btn-md btn-info"><i class="fa fa-floppy-o fa-lg"></i> <strong> Save Portrait</strong></button>
          <div id="scan">
            <video id="camera"></video>
            <canvas id="snap_shot"></canvas>
          </div>
        </div>

        <div class = "col-md-3"></div>
    </div>
	
    <div class="row top-buffer">
      <div class="text-center">
        <p><i>A Notification will appear if Facial Portrait is successfully captured.</i></p>
      </div>
      </div>
	 

	<div class="row" id="res_button">
			<div class="col-md-3"></div>
              <div class="col-md-6">
                <button id="scan_portrait" class="btn btn-lg btn-block btn-info">
                  <i class="fa fa-camera fa-lg"></i> Scan Portriat</button>
                <button id="verify_portrait" class="btn btn-lg btn-block btn-info">
                  <i class="fa fa-check fa-lg"></i> Verify Portriat</button>
              </div>
			<div class="col-md-3"></div>
    </div>	
	
    </div>
  </div>
  </div>


    <div class="row top-buffer scheme" id="Content">

        <!--Slide Show -->
  			<div id = "slideshow" class="carousel slide" data-ride="carousel">
  				<ol class="carousel-indicators">
      		<li data-target="slideshow" data-slide-to="0" class="active"></li>
      		<li data-target="slideshow" data-slide-to="1"></li>
      		<li data-target="slideshow" data-slide-to="2"></li>
      		<li data-target="slideshow" data-slide-to="3"></li>
    			</ol>


  				<div class="carousel-inner">

  				  <div class="item active">
  				    <img src="images/Vote.jpg" alt="TTTE image1">
  				    <div class="carousel-caption">
  				      <h3>Know your Political Paties</h3>
  				      <p>Vote to make a change.</p>
  				    </div>
  				  </div>

  				  <div class="item">
  				    <img src="images/NDC.jpg" alt="TTTE image2">
  				    <div class="carousel-caption">
  				      <h3>National Democratic Congress</h3>
  				      <p>The National Democratic Congress is a liberal centre-left political party</p>
  				    </div>
  				  </div>

  				  <div class="item">
  				    <img src="images/NNP.jpg" alt="TTTE image3">
  				    <div class="carousel-caption">
  				      <h3>New National Party</h3>
  				      <p>If you don't make your voice heard when it matters, you don't have the right to complain later.</p>
  				    </div>
  				  </div>

  				  <div class="item">
  				    <img src="images/parishes.jpg" alt="TTTE image4">
  				    <div class="carousel-caption">
  				      <h3>Grenada's Parishes</h3>
  				      <p>Know where your voting polls are going to be.</p>
  				    </div>
  				  </div>
  				</div>


  						<a class="left carousel-control" href="#slideshow" role="button" data-slide="prev">
  		    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
  		    <span class="sr-only">Previous</span>
  		  </a>
  		  <a class="right carousel-control" href="#slideshow" role="button" data-slide="next">
  		    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
  		    <span class="sr-only">Next</span>
  		  </a>
  		</div>

    </div>
	
	
	<div class="row top-buffer scheme" id="graph">
	
		<div id="chart-container"> 
			<canvas id="myCanvas"></canvas>
		</div>
	
	</div>


    <!--Modal Voting Section -->
		<div id="VotingModal" class="modal fade" role="dialog">
			<div class="modal-dialog modal-lg">

				<!--Content-->
				<div class="modal-content">
					<div class="modal-header">

						<h1 class="modal-title modal_window">Voting Screen</h1>

					</div>
					<div class="modal-body">

						<h2 class="modal_window">CAUTION</h2>
						<h4 class="modal_window">Please ensure that all interactions with this website from THIS POINT ON, will take place at an
						enclosed location in a discreet manner.</h4>

						<div class="container col-md-12">

							<h1 class="modal_window">CHOOSE YOUR PARTY</h1>

							<div class="col-md-7 col-offset-1">
							<label class="radio-inline" for="ndc">
								<input type="radio" name="ndc_vote" id="ndc" value="NDC"><img src="images/ndc-logo.jpg" alt="National Democratic Congress"/>
							</label>
						</div>

						<div class="col-md-5">
							<label class="radio-inline" for="nnp">
								<input type="radio" name="nnp_vote" id="nnp" value="NNP"><img src="images/nnp-logo.jpg" alt="New National Party"/>
							</label>
						</div>

						<input type="hidden" name="regNo" id="regNo" value="">

						<div class="row top-buffer modal_window" id="terms">
							<h4>By clicking Vote I acknowledged to have read and agreed to this website's<a href="">Terms and Conditions</a>.</h4>
						</div>

						</div>

						<div class="modal-footer">

						<div class="container col-md-12" id="vote_space">

						<div class="col-md-7 col-offset-5">
						<button class="btn btn-success" id="vote_button" onclick="return vote();">
							<i class="fa fa-check-circle fa-lg" aria-hidden="true"></i>Vote</button>
						</div>
						</div>

					</div>

					</div>
				</div>

			</div>
		</div>

	
    <div class="row text-center top-buffer scheme">

        <a href="" id="logo"><img class="img-responsive" src="images/Flag_Grenada.gif"></a>
        <p id="logo_n">This System was brought to you by<span id="signature"> Konnect</span>, Electronic Voting System.
  			<br>© 2016 Grenada's National Election Board - All Rights Reserved</p>
      </div>



  </div>

  <div class ="col-md-1">


  </div>


{% endblock %}
